stages:
  - build
  - deploy

default:
  image: go:alpine

build:
  stage: build
  script:
    - mkdir /root/app/kirito
    - cd /root/app/kirito
    - go mod tidy
    - make image-build
    - make docker-push

deploy:
  stage: deploy
  script:
    - docker pull antonykunaifi/aan-kirito:latest
    - kubectl apply -f kirito_manifest.yml
  environment: production

