stages:
  - build
  - deploy

default:
  image: go:alpine

build:
  stage: build
  script:
    - echo "This job builds something."

deploy:
  stage: deploy
  script:
    - echo "This job deploys something. It will only run when all jobs in the"
    - echo "test stage complete."
  environment: production

